# Generated by Django 6.0.3 on 2026-03-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='end_time',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_time',
            field=models.CharField(),
        ),
    ]
