# Generated by Django 6.0.3 on 2026-03-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
